id: switch_drukarka
alias: "Automatyczne wł/wył drukarki"
initial_state: 'on'
trigger:
  platform: state
  entity_id:
    - sensor.hp_laserjet_1300
  to: 'printing'
action:
    - service: script.turn_on
      entity_id: script.wl_drukarke
