id: switch_salon_tv
alias: "Włącz zasilanie - telewizor salon"
initial_state: 'on'
trigger:
  platform: state
  entity_id:
    - sensor.ir_salon
  to: !secret ir_kod_telewizora
condition: 
 - condition: state
   entity_id: switch.tv_salon
   state: 'off'
action:
    - service: switch.turn_on
      entity_id: switch.tv_salon
