id: switch_salon_tv
alias: "Wyłącz zasilanie - telewizor salon"
initial_state: 'on'
trigger:
  platform: state
  entity_id:
    - device_tracker.chromecast
  to: 'not_home'
  for: 
    minutes: 1
condition: 
 - condition: state
   entity_id: switch.tv_salon
   state: 'on'
action:
    - service: switch.turn_off
      entity_id: switch.tv_salon
    - service: script.wyl_osmc_salon
